export type itemList = {
  type: string;
  num: string;
  name: string;
};

export const itemLists: itemList[] = [
  {
    type: "program",
    num: "1",
    name: "สายการเรียนภาษา-ภาษาญี่ปุ่น",
  },
  {
    type: "program",
    num: "2",
    name: "สายการเรียนภาษา-ภาษาจีน",
  },
  {
    type: "program",
    num: "3",
    name: "สายการเรียนภาษา-ภาษาเกาหลี",
  },
  {
    type: "program",
    num: "4",
    name: "สายการเรียนภาษา-ภาษาสเปน",
  },
  {
    type: "program",
    num: "5",
    name: "สายการเรียนภาษา-ภาษาฝรั่งเศส",
  },
  {
    type: "program",
    num: "6",
    name: "สายการเรียนภาษา-ภาษาเยอรมัน",
  },
  {
    type: "program",
    num: "7",
    name: "สายการเรียนวิทยาศาสตร์-คณิตศาสตร์",
  },
  //program
  { type: "program", num: "8", name: "สายการเรียนภาษา-คณิตศาสตร์" },
  { type: "gifted", num: "9", name: "Gifted Science" },
  { type: "gifted", num: "10", name: "Gifted Math" },
  { type: "gifted", num: "11", name: "Gifted English" },
  { type: "gifted", num: "12", name: "Gifted Thai" },
  //club
  { type: "club", num: "13", name: "ชมรม Quant การเงินเชิงปริมาณ" },
  { type: "club", num: "14", name: "ชมรมคณิตศาสตร์" },
  { type: "club", num: "15", name: "ชมรมเพาะพันธุ์ไม้" },
  { type: "club", num: "16", name: "ชมรมการ์ตูน" },
  { type: "club", num: "17", name: "ชมรมสิ่งละอันพันละน้อย" },
  { type: "club", num: "18", name: "ชมรมสิ่งละอันพันละน้อย (โครเชต์)" },
  { type: "club", num: "19", name: "ชมรม Crossword" },
  { type: "club", num: "20", name: "ชมรมดนตรีสากล" },
  { type: "club", num: "21", name: "ชมรมภาพยนตร์สั้นและสื่อโทรทัศน์" },
  { type: "club", num: "22", name: "ชมรมผู้บำเพ็ญประโยชน์" },
  { type: "club", num: "23", name: "ชมรมวรรณศิลป์ ต.อ." },
  { type: "club", num: "24", name: "ชมรมสร้างสรรค์หนังสือ" },
  { type: "club", num: "25", name: "ชมรมนิเทศศิลป" },
  { type: "club", num: "26", name: "ชมรมจิตวิทยา" },
  { type: "club", num: "27", name: "ชมรมเพื่อนที่ปรึกษา" },
  { type: "club", num: "28", name: "ชมรม MUN" },
  { type: "club", num: "29", name: "ชมรม Debate" },
  { type: "club", num: "30", name: "ชมรมกฎหมายน่ารู้" },
  { type: "club", num: "31", name: "ชมรมหนังสังคม" },
  { type: "club", num: "32", name: "ชมรมภาคีสังคม" },
  { type: "club", num: "33", name: "ชมรมหลากทัศนะประวัติศาสตร์" },
  { type: "club", num: "34", name: "ชมรมสรรพศึกษา" },
  { type: "club", num: "35", name: "ชมรมบริหารธุรกิจ" },
  { type: "club", num: "36", name: "ชมรมศิลปศึกษา" },
  { type: "club", num: "37", name: "ชมรมของเล่นเพื่อการเรียนรู้" },
  { type: "club", num: "38", name: "ชมรมวิทยาศาสตร์" },
  { type: "club", num: "39", name: "ชมรมวิจัย" },
  { type: "club", num: "40", name: "ชมรมฟิตเนส" },
  { type: "club", num: "41", name: "ชมรมหมากกระดาน" },
  { type: "club", num: "42", name: "ชมรมผู้นำเยาวชนสาธารณสุข" },
  { type: "club", num: "43", name: "ชมรมผู้นำเชียร์" },
  { type: "club", num: "44", name: "ชมรมวาทศิลป์" },
  { type: "club", num: "45", name: "งานแนะแนว" },
  { type: "club", num: "46", name: "ชมรมถ่ายภาพ" },
  { type: "club", num: "47", name: "ชมรมภาษาไทย" },
  { type: "club", num: "48", name: "ชมรมภาษาเกาหลี" },
  { type: "club", num: "49", name: "ชมรมภาษาญี่ปุ่น" },
  { type: "club", num: "50", name: "ชมรมภาษาจีน" },
  { type: "club", num: "51", name: "ชมรมภาษาเยอรมัน" },
  { type: "club", num: "52", name: "ชมรมภาษาฝรั่งเศส" },
  { type: "club", num: "53", name: "ชมรมภาษาสเปน" },
  //organization
  { type: "organization", num: "54", name: "กลุ่มนักเรียนอาสาพยาบาล" },
  { type: "organization", num: "55", name: "คณะกรรมการหนังสืออนุสรณ์" },
  { type: "organization", num: "56", name: "สปค.ต.อ." },
  { type: "organization", num: "57", name: "สนตอ." },
  { type: "organization", num: "58", name: "สปค.รร.ต.อ." },
  { type: "organization", num: "59", name: "กช." },
  { type: "organization", num: "60", name: "กน." },
  { type: "organization", num: "61", name: "AIC" },
  { type: "organization", num: "62", name: "สโมสรอาจารย์โรงเรียนฯ" },
  { type: "organization", num: "63", name: "TUPRO" },
  //outer
  { type: "outer", num: "64", name: "องค์กรภายนอก" },
  { type: "outer", num: "65", name: "องค์กรภายนอก" },
  { type: "outer", num: "66", name: "องค์กรภายนอก" },
  { type: "outer", num: "67", name: "องค์กรภายนอก" },
  { type: "outer", num: "68", name: "องค์กรภายนอก" },
  { type: "outer", num: "69", name: "องค์กรภายนอก" },
  { type: "outer", num: "70", name: "องค์กรภายนอก" },
  { type: "outer", num: "71", name: "องค์กรภายนอก" },
  { type: "outer", num: "72", name: "องค์กรภายนอก" },
  { type: "outer", num: "73", name: "องค์กรภายนอก" },
  { type: "outer", num: "74", name: "องค์กรภายนอก" },
  { type: "outer", num: "75", name: "องค์กรภายนอก" },
  { type: "outer", num: "76", name: "องค์กรภายนอก" },
  { type: "outer", num: "77", name: "องค์กรภายนอก" },
  { type: "outer", num: "78", name: "องค์กรภายนอก" },
  { type: "outer", num: "79", name: "องค์กรภายนอก" },
  { type: "outer", num: "80", name: "องค์กรภายนอก" },
  { type: "outer", num: "81", name: "องค์กรภายนอก" },
  { type: "outer", num: "82", name: "องค์กรภายนอก" },
  { type: "outer", num: "83", name: "องค์กรภายนอก" },
  { type: "outer", num: "84", name: "องค์กรภายนอก" },
  { type: "outer", num: "85", name: "องค์กรภายนอก" },
  { type: "outer", num: "86", name: "องค์กรภายนอก" },
  { type: "outer", num: "87", name: "องค์กรภายนอก" },
  { type: "outer", num: "88", name: "องค์กรภายนอก" },
  { type: "outer", num: "89", name: "องค์กรภายนอก" },
  { type: "outer", num: "90", name: "องค์กรภายนอก" },
  { type: "outer", num: "91", name: "องค์กรภายนอก" },
];
